services:
  - type: web
    name: smc-predictor
    runtime: python
    rootDir: smc
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --chdir webapp --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: TV_USERNAME
        sync: false
      - key: TV_PASSWORD
        sync: false
      - key: PYTHON_VERSION
        value: 3.13.0
